project:
  type: book
  output-dir: _book

book:
  title: "Introduction to Data Science using Python"
  author: 
    - "Lindsay Forestell" 
    - "Stuart Hemerling"
  date: "2022-10-12"

  #reader-mode: true

  repo-url: https://github.com/bcgov/ds-intro-to-python
  repo-branch: main
  repo-actions: [source, edit, issue]
  sharing: [twitter, facebook]
  cover-image: cover.png
  #downloads: [pdf]

  chapters:
    - index.qmd

    - 00_introduction_to_python.qmd

    - 13_working_with_code.qmd 
    - 02_core_data_structure_concepts.qmd
    - 21_getting_data_with_pandas.qmd
    
    - 31_exploring_data_structures.qmd
    - 32_graphical_depictions_of_data.qmd
    
    - 30_bcdata.qmd
   
    - 34_machine_learning.qmd

    - 01_working_with_code.qmd 
    - 02_core_data_structure_concepts.qmd

    - 11_getting_data_with_pandas.qmd
    - 12_cleaning_it_up.qmd

    - 21_exploring_data_structures.qmd
    - 22_graphical_depictions_of_data.qmd

    - 31_bcdata.qmd
    - 32_advanced_pandas.qmd
    - 33_create_reports.qmd


    - references.qmd

  sidebar:
    style: "docked"
    logo: cover.png
    background: dark

  navbar:
    logo: BCID_H_rgb_rev.png
    title: false
    collapse-below: lg
    left:
      - text: "Home"
        href: index.qmd
      - text: "Introduction to Python"
        menu:
          - text: Getting Up and Running
            href: 00_introduction_to_python.qmd
          - text: Working with Code

            href: 13_working_with_code.qmd
            href: 01_working_with_code.qmd

          - text: Core Concepts
            href: 02_core_data_structure_concepts.qmd
      - text: "Get and Clean Data"
        menu:    
          - text: Getting Data with Pandas

            href: 21_getting_data_with_pandas.qmd
      - text: "Understand and Analyze Data"
        menu:
          - text: Exploring Data Structures
            href: 31_exploring_data_structures.qmd
          - text: Graphical Depictions of Data
            href: 32_graphical_depictions_of_data.qmd      
      - text: "Advanced Topics"
        menu:
          - text: "bcdata package"
            href: 30_bcdata.qmd
          - text: "Machine Learning"
            href: 34_machine_learning.qmd

            href: 11_getting_data_with_pandas.qmd
          - text: Cleaning Data with Pandas
            href: 12_cleaning_it_up.qmd
      - text: "Understand and Analyze Data"
        menu:
          - text: Exploring Data Structures
            href: 21_exploring_data_structures.qmd
          - text: Graphical Depictions of Data
            href: 22_graphical_depictions_of_data.qmd      
      - text: "Advanced Topics"
        menu:
          - text: "bcdata package"
            href: 31_bcdata.qmd
          - text: "Advanced Pandas"
            href: 32_advanced_pandas.qmd
          - text: "Creating Reports"
            href: 33_create_reports.qmd

      - text: "References"
        href: references.qmd
    right:
      - icon: share

  page-footer:
    left: |
      Introduction to Data Science using Python was written by <br>
      Lindsay Forestell and Stuart Hemerling 
    center: 
      - text: "License"
        href: license.qmd
      - text: "Python for Data Science Course"
        href: https://bcgov.github.io/ds-intro-to-python/index.html
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.

bibliography: references.bib
csl-entry-spacing: 2em

toc: true
toc-title: On this page
number-sections: true
number-depth: 2
toc-depth: 4

code-fold: false
code-overflow: scroll

format:
  html:
    theme:
      light: flatly
      dark: darkly


