project:
  type: book

book:
  title: "Introduction to Data Science using Python"
  author: 
    - "Lindsay Forestell" 
    - "Stuart Hemerling"
  date: "2022-10-12"
  chapters:
    - index.qmd
    - part: "Introduction to Python"
      chapters:
        - 00_introduction_to_python.qmd
        - 02_core_data_structure_concepts.qmd
    - part: "Get and Clean Data"
      chapters:
        - 21_getting_data_with_pandas.qmd
    - part: "Understand and Analyze Data"
      chapters:
       - 32_graphical_depictions_of_data.qmd
    - part: "Advanced Topics"
      chapters:
        - 30_bcdata.qmd
    - references.qmd

bibliography: references.bib

toc: true
number-sections: true
number-depth: 2
toc-depth: 4

code-fold: false
code-overflow: scroll

format:
  html:
    theme: cosmo


